// R10R16 — fonte canônica dos contratos operacionais do Orchestrator.
// Runtime, renderização do Wrangler, smoke tests e testes de regressão devem
// derivar deste arquivo. Duplicações residuais (ex.: package.json) são apenas
// metadados e são bloqueadas por testes de drift.
export const ORCHESTRATOR_CONTRACT = Object.freeze({
  service: 'formula-do-gol-orchestrator',
  version: '2.4.0',
  configSchemaVersion: 8,
  cron: '*/5 * * * *',
  reliability: Object.freeze({
    controlPlane: true,
    version: 1,
    sportingIntegrityGuard: true,
    sportingIntegrityVersion: 1,
    diagnosticArtifact: true,
    incidentRegressionSuite: true,
    correlationId: true,
    healthStates: ['CORE_GREEN', 'ENRICHMENT_PENDING', 'DEGRADED', 'CRITICAL'],
    sloMinutes: Object.freeze({
      finalToDetection: 5,
      finalToResults: 7,
      finalToAf: 10,
      commitToSite: 5,
      editorialClosure: 15,
    }),
  }),
  health: Object.freeze({
    liveBrowserUntouched: true,
    liveBrowserRefreshSeconds: 30,
    githubHeartbeatRemoved: true,
    transmissionGuardian: true,
    transmissionGuardianCheckpointsMinutes: [-90, -15, 10],
    transmissionGuardianNeedGate: true,
    transmissionGuardianBatching: true,
    transmissionNeedDrivenV2: true,
    adaptiveSlowPath: true,
    adaptiveSlowPathMaxSleepMinutes: 60,
    transmissionTvOperationalWindowHours: 72,
    transmissionTvCheckpointsMinutes: [-4320, -1440, -360],
    transmissionPlayerCheckpointsMinutes: [-90, -15, 10],
    transmissionYoutubeOnlyWhenRequired: true,
    publicFirstAttemptAfterFinalMinutes: 15,
    postgameFastlanePrimary: true,
    postgameAiRoutingVersion: 6,
    postgameAiGateway: true,
    postgameGeminiPrimarySearch: true,
    postgameWorkersAiExtraction: true,
    postgameOpenAiFallbackOnly: true,
    postgameFastlaneCronMinutes: 1,
    dormantMode: true,
    postgameConcreteGate: true,
    postgameAutomaticWindowHours: null,
    postgamePublicPersistentUntilResolved: true,
    postgamePublicSlaMinutes: 120,
    postgameGithubMaxDispatchesPerEvent: 2,
    postgameHighlightsBatching: true,
    targetedPublicResearch: true,
    continentalPhaseFingerprints: true,
    continentalAgendaAware: true,
    continentalStateIdempotency: true,
    continentalEditorialSingleAuthority: true,
    continentalHighlightsIndependent: true,
    continentalDailyFallbackMinutes: 1440,
    continentalJointBrazilianClosure: true,
    continentalPairPhaseReconciliation: true,
    continentalAiAuditWorkflow: true,
    brasileiraoSourceCircuitBreaker: true,
    brasileiraoSourceProbeMinutes: 5,
    espnScoreboardGateway: true,
    afPostFinalFastlane: true,
    afPostFinalFastlaneVersion: 1,
    afPostFinalFastlaneWorkflow: 'af-previsao-fastlane-pos-final.yml',
    afPostFinalFullReconciliationQueued: true,
    editorialClosureGuarantee: true,
    editorialClosureGuaranteeVersion: 1,
    editorialClosureSlaMinutes: 15,
    editorialClosureCronMinutes: 5,
    editorialClosurePriority: 'after-final-before-enrichment',
    editorialClosureWriterSafe: true,
    reliabilityControlPlane: true,
    reliabilityControlPlaneVersion: 1,
    sportingSnapshotIntegrityGuard: true,
    sportingSnapshotIntegrityGuardVersion: 1,
    reliabilityDiagnosticArtifact: true,
    reliabilityIncidentRegressionSuite: true,
    reliabilityCorrelationId: true,
    reliabilityHealthStates: ['CORE_GREEN', 'ENRICHMENT_PENDING', 'DEGRADED', 'CRITICAL'],
    reliabilityFinalToDetectionSloMinutes: 5,
    reliabilityFinalToResultsSloMinutes: 7,
    reliabilityFinalToAfSloMinutes: 10,
    reliabilityCommitToSiteSloMinutes: 5,
  }),
});

export function orchestratorHealth(mode = 'shadow') {
  return {
    ok: true,
    service: ORCHESTRATOR_CONTRACT.service,
    version: ORCHESTRATOR_CONTRACT.version,
    mode: String(mode || 'shadow'),
    cron: ORCHESTRATOR_CONTRACT.cron,
    ...ORCHESTRATOR_CONTRACT.health,
  };
}

export function correlationIdForEvent(eventId, suffix = '') {
  const clean = String(eventId || '').replace(/[^a-zA-Z0-9._-]/g, '').slice(0, 80);
  const tail = String(suffix || '').replace(/[^a-zA-Z0-9._-]/g, '').slice(0, 40);
  return `fdg-${clean || 'unknown'}${tail ? `-${tail}` : ''}`;
}
